//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIClientImport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string TestOrProd {
            get {
                return ((string)(this["TestOrProd"]));
            }
            set {
                this["TestOrProd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=cindsv91002\\SimsTst;Initial Catalog=Sims;User ID=SVCL_SIMS_SQL_JRE;Pa" +
            "ssword=SimsTstPW;persist security info=False")]
        public string TestConnectionString {
            get {
                return ((string)(this["TestConnectionString"]));
            }
            set {
                this["TestConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=DCTASV21001;initial catalog=SI;User ID=dotnetuser;Password=471$$WeSt;" +
            "persist security info=False")]
        public string ProdConnectionString {
            get {
                return ((string)(this["ProdConnectionString"]));
            }
            set {
                this["ProdConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultFileLocation {
            get {
                return ((string)(this["DefaultFileLocation"]));
            }
            set {
                this["DefaultFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=(local);initial catalog=SI;User ID=dotnetuser;Password=471$$WeSt;pers" +
            "ist security info=False")]
        public string LocalConnectionString {
            get {
                return ((string)(this["LocalConnectionString"]));
            }
            set {
                this["LocalConnectionString"] = value;
            }
        }
    }
}
